# pyproject.toml
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lib_functions"
version = "0.1.0"
description = "..."
authors = [{ name="AIforChip", email="ai@chip.com" }]
dependencies = [
  # e.g. "numpy>=1.20"
]
