#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("nr", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("nq", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("np", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("A_address0", 14, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("A_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("A_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("A_d0", 64, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("A_q0", 64, hls_in, 3, "ap_memory", "in_data", 1),
	Port_Property("A_address1", 14, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("A_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("A_q1", 64, hls_in, 3, "ap_memory", "in_data", 1),
	Port_Property("C4_address0", 10, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("C4_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("C4_q0", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("C4_address1", 10, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("C4_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("C4_q1", 64, hls_in, 4, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("sum_address0", 5, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("sum_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("sum_we0", 1, hls_out, 5, "ap_memory", "mem_we", 1),
	Port_Property("sum_d0", 64, hls_out, 5, "ap_memory", "mem_din", 1),
	Port_Property("sum_q0", 64, hls_in, 5, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "doitgen";
