#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("force_x_address0", 10, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("force_x_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("force_x_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("force_x_d0", 64, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("force_y_address0", 10, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("force_y_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("force_y_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("force_y_d0", 64, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("force_z_address0", 10, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("force_z_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("force_z_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("force_z_d0", 64, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("position_x_address0", 10, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("position_x_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("position_x_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("position_y_address0", 10, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("position_y_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("position_y_q0", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("position_z_address0", 10, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("position_z_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("position_z_q0", 64, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("NL_address0", 18, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("NL_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("NL_q0", 32, hls_in, 6, "ap_memory", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "md_knn";
