// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="aes256_encrypt_ecb_aes256_encrypt_ecb,hls_ip_2022_2_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.649000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26819,HLS_SYN_LUT=213492,HLS_VERSION=2022_2_2}" *)

module aes256_encrypt_ecb (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ctx_i,
        ctx_o,
        ctx_o_ap_vld,
        k_address0,
        k_ce0,
        k_q0,
        buf_r_address0,
        buf_r_ce0,
        buf_r_we0,
        buf_r_d0,
        buf_r_q0,
        buf_r_address1,
        buf_r_ce1,
        buf_r_we1,
        buf_r_d1,
        buf_r_q1
);

parameter    ap_ST_fsm_state1 = 44'd1;
parameter    ap_ST_fsm_state2 = 44'd2;
parameter    ap_ST_fsm_state3 = 44'd4;
parameter    ap_ST_fsm_state4 = 44'd8;
parameter    ap_ST_fsm_state5 = 44'd16;
parameter    ap_ST_fsm_state6 = 44'd32;
parameter    ap_ST_fsm_state7 = 44'd64;
parameter    ap_ST_fsm_state8 = 44'd128;
parameter    ap_ST_fsm_state9 = 44'd256;
parameter    ap_ST_fsm_state10 = 44'd512;
parameter    ap_ST_fsm_state11 = 44'd1024;
parameter    ap_ST_fsm_state12 = 44'd2048;
parameter    ap_ST_fsm_state13 = 44'd4096;
parameter    ap_ST_fsm_state14 = 44'd8192;
parameter    ap_ST_fsm_state15 = 44'd16384;
parameter    ap_ST_fsm_state16 = 44'd32768;
parameter    ap_ST_fsm_state17 = 44'd65536;
parameter    ap_ST_fsm_state18 = 44'd131072;
parameter    ap_ST_fsm_state19 = 44'd262144;
parameter    ap_ST_fsm_state20 = 44'd524288;
parameter    ap_ST_fsm_state21 = 44'd1048576;
parameter    ap_ST_fsm_state22 = 44'd2097152;
parameter    ap_ST_fsm_state23 = 44'd4194304;
parameter    ap_ST_fsm_state24 = 44'd8388608;
parameter    ap_ST_fsm_state25 = 44'd16777216;
parameter    ap_ST_fsm_state26 = 44'd33554432;
parameter    ap_ST_fsm_state27 = 44'd67108864;
parameter    ap_ST_fsm_state28 = 44'd134217728;
parameter    ap_ST_fsm_state29 = 44'd268435456;
parameter    ap_ST_fsm_state30 = 44'd536870912;
parameter    ap_ST_fsm_state31 = 44'd1073741824;
parameter    ap_ST_fsm_state32 = 44'd2147483648;
parameter    ap_ST_fsm_state33 = 44'd4294967296;
parameter    ap_ST_fsm_state34 = 44'd8589934592;
parameter    ap_ST_fsm_state35 = 44'd17179869184;
parameter    ap_ST_fsm_state36 = 44'd34359738368;
parameter    ap_ST_fsm_state37 = 44'd68719476736;
parameter    ap_ST_fsm_state38 = 44'd137438953472;
parameter    ap_ST_fsm_state39 = 44'd274877906944;
parameter    ap_ST_fsm_state40 = 44'd549755813888;
parameter    ap_ST_fsm_state41 = 44'd1099511627776;
parameter    ap_ST_fsm_state42 = 44'd2199023255552;
parameter    ap_ST_fsm_state43 = 44'd4398046511104;
parameter    ap_ST_fsm_state44 = 44'd8796093022208;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [767:0] ctx_i;
output  [767:0] ctx_o;
output   ctx_o_ap_vld;
output  [4:0] k_address0;
output   k_ce0;
input  [7:0] k_q0;
output  [3:0] buf_r_address0;
output   buf_r_ce0;
output   buf_r_we0;
output  [7:0] buf_r_d0;
input  [7:0] buf_r_q0;
output  [3:0] buf_r_address1;
output   buf_r_ce1;
output   buf_r_we1;
output  [7:0] buf_r_d1;
input  [7:0] buf_r_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[767:0] ctx_o;
reg ctx_o_ap_vld;
reg[3:0] buf_r_address0;
reg buf_r_ce0;
reg buf_r_we0;
reg[7:0] buf_r_d0;
reg[3:0] buf_r_address1;
reg buf_r_ce1;
reg buf_r_we1;
reg[7:0] buf_r_d1;

(* fsm_encoding = "none" *) reg   [43:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [767:0] reg_411;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln148_fu_553_p2;
wire    ap_CS_fsm_state21;
wire   [0:0] tmp_fu_564_p3;
wire   [0:0] trunc_ln148_fu_593_p1;
reg   [767:0] reg_417;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln142_fu_500_p2;
reg   [7:0] reg_423;
reg   [7:0] reg_428;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state32;
reg   [7:0] reg_433;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state37;
reg   [7:0] reg_440;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state33;
reg   [7:0] reg_447;
reg   [7:0] reg_452;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state34;
reg   [7:0] reg_457;
reg   [7:0] reg_462;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state35;
reg   [7:0] reg_467;
reg   [7:0] reg_472;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state36;
reg   [7:0] reg_477;
reg   [767:0] reg_482;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state6;
reg   [3:0] buf_r_addr_12_reg_1047;
wire   [3:0] trunc_ln102_fu_572_p1;
reg   [3:0] trunc_ln102_reg_1052;
reg   [3:0] buf_r_addr_13_reg_1058;
wire   [4:0] add_ln100_fu_587_p2;
reg   [4:0] add_ln100_reg_1063;
reg   [0:0] trunc_ln148_reg_1068;
reg   [3:0] buf_r_addr_14_reg_1072;
reg   [3:0] buf_r_addr_15_reg_1077;
wire   [7:0] xor_ln105_1_fu_762_p2;
reg   [7:0] xor_ln105_1_reg_1082;
wire    ap_CS_fsm_state23;
wire   [7:0] xor_ln105_3_fu_802_p2;
reg   [7:0] xor_ln105_3_reg_1087;
reg   [7:0] rcon_3_reg_1092;
reg   [3:0] buf_r_addr_17_reg_1097;
wire    ap_CS_fsm_state26;
wire   [3:0] add_ln71_1_fu_813_p2;
reg   [3:0] add_ln71_1_reg_1103;
reg   [3:0] buf_r_addr_16_reg_1111;
wire    ap_CS_fsm_state28;
wire   [3:0] add_ln71_fu_878_p2;
reg   [3:0] add_ln71_reg_1117;
wire    grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start;
wire    grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_done;
wire    grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_idle;
wire    grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_ready;
wire   [4:0] grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_k_address0;
wire    grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_k_ce0;
wire   [767:0] grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_p_partset613_out_o;
wire    grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_p_partset613_out_o_ap_vld;
wire    grp_aes_expandEncKey_fu_362_ap_start;
wire    grp_aes_expandEncKey_fu_362_ap_done;
wire    grp_aes_expandEncKey_fu_362_ap_idle;
wire    grp_aes_expandEncKey_fu_362_ap_ready;
reg   [767:0] grp_aes_expandEncKey_fu_362_p_read;
reg   [9:0] grp_aes_expandEncKey_fu_362_k_idx;
reg   [7:0] grp_aes_expandEncKey_fu_362_rc_read;
wire   [767:0] grp_aes_expandEncKey_fu_362_ap_return_0;
wire   [7:0] grp_aes_expandEncKey_fu_362_ap_return_1;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_done;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_idle;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_ready;
wire   [3:0] grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_address0;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_ce0;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_we0;
wire   [7:0] grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_d0;
wire   [3:0] grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_address1;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_ce1;
wire   [767:0] grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_or_ln79_1_out;
wire    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_or_ln79_1_out_ap_vld;
wire    grp_aes_subBytes_1_fu_380_ap_start;
wire    grp_aes_subBytes_1_fu_380_ap_done;
wire    grp_aes_subBytes_1_fu_380_ap_idle;
wire    grp_aes_subBytes_1_fu_380_ap_ready;
wire   [3:0] grp_aes_subBytes_1_fu_380_buf_r_address0;
wire    grp_aes_subBytes_1_fu_380_buf_r_ce0;
wire    grp_aes_subBytes_1_fu_380_buf_r_we0;
wire   [7:0] grp_aes_subBytes_1_fu_380_buf_r_d0;
wire    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start;
wire    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_done;
wire    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_idle;
wire    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_ready;
wire   [3:0] grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_address0;
wire    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_ce0;
wire    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_we0;
wire   [7:0] grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_d0;
wire   [3:0] grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_address1;
wire    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_ce1;
reg   [4:0] i_15_reg_318;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state20;
reg   [3:0] i_16_reg_329;
wire    ap_CS_fsm_state27;
wire   [0:0] icmp_ln71_1_fu_848_p2;
reg   [3:0] i_17_reg_341;
wire    ap_CS_fsm_state29;
wire   [0:0] icmp_ln71_fu_918_p2;
reg    grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [767:0] ctx7_fu_132;
reg    grp_aes_expandEncKey_fu_362_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [767:0] or_ln79_1_loc_fu_136;
reg    grp_aes_subBytes_1_fu_380_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start_reg;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
wire   [63:0] zext_ln100_fu_559_p1;
wire   [63:0] zext_ln102_fu_582_p1;
wire   [63:0] zext_ln102_1_fu_601_p1;
wire   [63:0] zext_ln102_2_fu_611_p1;
wire   [63:0] zext_ln71_3_fu_808_p1;
wire   [63:0] zext_ln71_fu_873_p1;
reg   [2:0] i_7_fu_124;
wire   [2:0] add_ln142_fu_510_p2;
reg   [7:0] rcon_2_fu_128;
reg   [3:0] i_11_fu_140;
wire   [3:0] i_23_fu_863_p2;
reg   [767:0] empty_24_fu_144;
reg   [7:0] rcon_1_fu_148;
reg    ap_block_state30_on_subcall_done;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire   [7:0] xor_ln104_1_fu_668_p2;
wire   [7:0] xor_ln104_4_fu_715_p2;
wire   [7:0] xor_ln71_1_fu_841_p2;
wire   [7:0] xor_ln71_fu_911_p2;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state42;
wire   [3:0] or_ln102_fu_576_p2;
wire   [3:0] or_ln102_1_fu_596_p2;
wire   [3:0] or_ln102_2_fu_606_p2;
wire   [7:0] xor_ln103_fu_616_p2;
wire   [7:0] xor_ln103_1_fu_622_p2;
wire   [7:0] shl_ln55_fu_642_p2;
wire   [0:0] tmp_34_fu_634_p3;
wire   [7:0] xor_ln55_fu_648_p2;
wire   [7:0] e_fu_628_p2;
wire   [7:0] select_ln55_fu_654_p3;
wire   [7:0] xor_ln104_fu_662_p2;
wire   [7:0] xor_ln104_2_fu_675_p2;
wire   [7:0] shl_ln55_1_fu_689_p2;
wire   [0:0] tmp_35_fu_681_p3;
wire   [7:0] xor_ln55_1_fu_695_p2;
wire   [7:0] select_ln55_1_fu_701_p3;
wire   [7:0] xor_ln104_3_fu_709_p2;
wire   [7:0] xor_ln105_2_fu_722_p2;
wire   [7:0] shl_ln55_2_fu_736_p2;
wire   [0:0] tmp_36_fu_728_p3;
wire   [7:0] xor_ln55_2_fu_742_p2;
wire   [7:0] select_ln55_2_fu_748_p3;
wire   [7:0] xor_ln105_fu_756_p2;
wire   [7:0] xor_ln105_4_fu_768_p2;
wire   [7:0] shl_ln55_3_fu_782_p2;
wire   [0:0] tmp_37_fu_774_p3;
wire   [7:0] xor_ln55_3_fu_788_p2;
wire   [7:0] select_ln55_3_fu_794_p3;
wire   [6:0] shl_ln71_1_fu_819_p3;
wire   [767:0] zext_ln71_1_fu_827_p1;
wire   [767:0] lshr_ln71_1_fu_831_p2;
wire   [7:0] trunc_ln71_1_fu_837_p1;
wire   [7:0] zext_ln71_2_cast_fu_887_p4;
wire   [767:0] zext_ln71_2_fu_897_p1;
wire   [767:0] lshr_ln71_fu_901_p2;
wire   [7:0] trunc_ln71_fu_907_p1;
reg   [43:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 44'd1;
#0 grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start_reg = 1'b0;
#0 grp_aes_expandEncKey_fu_362_ap_start_reg = 1'b0;
#0 grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start_reg = 1'b0;
#0 grp_aes_subBytes_1_fu_380_ap_start_reg = 1'b0;
#0 grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start_reg = 1'b0;
end

aes256_encrypt_ecb_aes256_encrypt_ecb_Pipeline_ecb1 grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start),
    .ap_done(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_done),
    .ap_idle(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_idle),
    .ap_ready(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_ready),
    .ctx_load(reg_411),
    .k_address0(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_k_address0),
    .k_ce0(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_k_ce0),
    .k_q0(k_q0),
    .p_partset613_out_i(ctx7_fu_132),
    .p_partset613_out_o(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_p_partset613_out_o),
    .p_partset613_out_o_ap_vld(grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_p_partset613_out_o_ap_vld)
);

aes256_encrypt_ecb_aes_expandEncKey grp_aes_expandEncKey_fu_362(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_expandEncKey_fu_362_ap_start),
    .ap_done(grp_aes_expandEncKey_fu_362_ap_done),
    .ap_idle(grp_aes_expandEncKey_fu_362_ap_idle),
    .ap_ready(grp_aes_expandEncKey_fu_362_ap_ready),
    .p_read(grp_aes_expandEncKey_fu_362_p_read),
    .k_idx(grp_aes_expandEncKey_fu_362_k_idx),
    .rc_read(grp_aes_expandEncKey_fu_362_rc_read),
    .ap_return_0(grp_aes_expandEncKey_fu_362_ap_return_0),
    .ap_return_1(grp_aes_expandEncKey_fu_362_ap_return_1)
);

aes256_encrypt_ecb_aes256_encrypt_ecb_Pipeline_cpkey grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start),
    .ap_done(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_done),
    .ap_idle(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_idle),
    .ap_ready(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_ready),
    .ctx7(reg_417),
    .buf_r_address0(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_address0),
    .buf_r_ce0(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_ce0),
    .buf_r_we0(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_we0),
    .buf_r_d0(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_d0),
    .buf_r_address1(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_address1),
    .buf_r_ce1(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_ce1),
    .buf_r_q1(buf_r_q1),
    .or_ln79_1_out(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_or_ln79_1_out),
    .or_ln79_1_out_ap_vld(grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_or_ln79_1_out_ap_vld)
);

aes256_encrypt_ecb_aes_subBytes_1 grp_aes_subBytes_1_fu_380(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_subBytes_1_fu_380_ap_start),
    .ap_done(grp_aes_subBytes_1_fu_380_ap_done),
    .ap_idle(grp_aes_subBytes_1_fu_380_ap_idle),
    .ap_ready(grp_aes_subBytes_1_fu_380_ap_ready),
    .buf_r_address0(grp_aes_subBytes_1_fu_380_buf_r_address0),
    .buf_r_ce0(grp_aes_subBytes_1_fu_380_buf_r_ce0),
    .buf_r_we0(grp_aes_subBytes_1_fu_380_buf_r_we0),
    .buf_r_d0(grp_aes_subBytes_1_fu_380_buf_r_d0),
    .buf_r_q0(buf_r_q0)
);

aes256_encrypt_ecb_aes256_encrypt_ecb_Pipeline_addkey grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start),
    .ap_done(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_done),
    .ap_idle(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_idle),
    .ap_ready(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_ready),
    .ctx_ret(reg_482),
    .buf_r_address0(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_address0),
    .buf_r_ce0(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_ce0),
    .buf_r_we0(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_we0),
    .buf_r_d0(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_d0),
    .buf_r_address1(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_address1),
    .buf_r_ce1(grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_ce1),
    .buf_r_q1(buf_r_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state43)) begin
            grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start_reg <= 1'b1;
        end else if ((grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_ready == 1'b1)) begin
            grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd1))) begin
            grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start_reg <= 1'b1;
        end else if ((grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_ready == 1'b1)) begin
            grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start_reg <= 1'b1;
        end else if ((grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_ready == 1'b1)) begin
            grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_expandEncKey_fu_362_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln148_fu_553_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state21) & (trunc_ln148_fu_593_p1 == 1'd0) & (tmp_fu_564_p3 == 1'd1)))) begin
            grp_aes_expandEncKey_fu_362_ap_start_reg <= 1'b1;
        end else if ((grp_aes_expandEncKey_fu_362_ap_ready == 1'b1)) begin
            grp_aes_expandEncKey_fu_362_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_subBytes_1_fu_380_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln148_fu_553_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln148_fu_553_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
            grp_aes_subBytes_1_fu_380_ap_start_reg <= 1'b1;
        end else if ((grp_aes_subBytes_1_fu_380_ap_ready == 1'b1)) begin
            grp_aes_subBytes_1_fu_380_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_aes_expandEncKey_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ctx7_fu_132 <= grp_aes_expandEncKey_fu_362_ap_return_0;
    end else if (((grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_p_partset613_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ctx7_fu_132 <= grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_p_partset613_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        empty_24_fu_144 <= or_ln79_1_loc_fu_136;
    end else if (((icmp_ln71_1_fu_848_p2 == 1'd1) & (trunc_ln148_reg_1068 == 1'd0) & (1'b1 == ap_CS_fsm_state27))) begin
        empty_24_fu_144 <= reg_482;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd1))) begin
        i_11_fu_140 <= 4'd1;
    end else if (((1'b1 == ap_CS_fsm_state27) & ((icmp_ln71_1_fu_848_p2 == 1'd1) | (trunc_ln148_reg_1068 == 1'd1)))) begin
        i_11_fu_140 <= i_23_fu_863_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        i_15_reg_318 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        i_15_reg_318 <= add_ln100_reg_1063;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_aes_expandEncKey_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        i_16_reg_329 <= 4'd15;
    end else if (((icmp_ln71_1_fu_848_p2 == 1'd0) & (trunc_ln148_reg_1068 == 1'd0) & (1'b1 == ap_CS_fsm_state27))) begin
        i_16_reg_329 <= add_ln71_1_reg_1103;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (trunc_ln148_fu_593_p1 == 1'd1) & (tmp_fu_564_p3 == 1'd1))) begin
        i_17_reg_341 <= 4'd15;
    end else if (((icmp_ln71_fu_918_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state29))) begin
        i_17_reg_341 <= add_ln71_reg_1117;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_7_fu_124 <= 3'd7;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd0))) begin
        i_7_fu_124 <= add_ln142_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd1))) begin
        rcon_1_fu_148 <= 8'd1;
    end else if (((icmp_ln71_1_fu_848_p2 == 1'd1) & (trunc_ln148_reg_1068 == 1'd0) & (1'b1 == ap_CS_fsm_state27))) begin
        rcon_1_fu_148 <= rcon_3_reg_1092;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        rcon_2_fu_128 <= 8'd1;
    end else if (((grp_aes_expandEncKey_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rcon_2_fu_128 <= grp_aes_expandEncKey_fu_362_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15))) begin
        reg_433 <= buf_r_q1;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_433 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15))) begin
        reg_440 <= buf_r_q0;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_440 <= buf_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (tmp_fu_564_p3 == 1'd0))) begin
        add_ln100_reg_1063 <= add_ln100_fu_587_p2;
        buf_r_addr_12_reg_1047 <= zext_ln100_fu_559_p1;
        buf_r_addr_13_reg_1058[3 : 1] <= zext_ln102_fu_582_p1[3 : 1];
        trunc_ln102_reg_1052 <= trunc_ln102_fu_572_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        add_ln71_1_reg_1103 <= add_ln71_1_fu_813_p2;
        buf_r_addr_17_reg_1097 <= zext_ln71_3_fu_808_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        add_ln71_reg_1117 <= add_ln71_fu_878_p2;
        buf_r_addr_16_reg_1111 <= zext_ln71_fu_873_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_r_addr_14_reg_1072[0] <= zext_ln102_1_fu_601_p1[0];
buf_r_addr_14_reg_1072[3 : 2] <= zext_ln102_1_fu_601_p1[3 : 2];
        buf_r_addr_15_reg_1077[3 : 2] <= zext_ln102_2_fu_611_p1[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_or_ln79_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        or_ln79_1_loc_fu_136 <= grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_or_ln79_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        rcon_3_reg_1092 <= grp_aes_expandEncKey_fu_362_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) | ((icmp_ln148_fu_553_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state21) & (trunc_ln148_fu_593_p1 == 1'd0) & (tmp_fu_564_p3 == 1'd1)))) begin
        reg_411 <= ctx_i;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd0)))) begin
        reg_417 <= ctx7_fu_132;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln148_fu_553_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state21) & (trunc_ln148_fu_593_p1 == 1'd0) & (tmp_fu_564_p3 == 1'd1)))) begin
        reg_423 <= rcon_1_fu_148;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_428 <= buf_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_447 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_452 <= buf_r_q1;
        reg_457 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state13))) begin
        reg_462 <= buf_r_q1;
        reg_467 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14))) begin
        reg_472 <= buf_r_q1;
        reg_477 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25))) begin
        reg_482 <= grp_aes_expandEncKey_fu_362_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (tmp_fu_564_p3 == 1'd1))) begin
        trunc_ln148_reg_1068 <= trunc_ln148_fu_593_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        xor_ln105_1_reg_1082 <= xor_ln105_1_fu_762_p2;
        xor_ln105_3_reg_1087 <= xor_ln105_3_fu_802_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

always @ (*) begin
    if ((grp_aes_expandEncKey_fu_362_ap_done == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state30_on_subcall_done)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

always @ (*) begin
    if ((grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_done == 1'b0)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_aes_expandEncKey_fu_362_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_aes_subBytes_1_fu_380_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        buf_r_address0 = zext_ln71_fu_873_p1;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        buf_r_address0 = zext_ln71_3_fu_808_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_address0 = buf_r_addr_15_reg_1077;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        buf_r_address0 = buf_r_addr_13_reg_1058;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_r_address0 = zext_ln102_2_fu_611_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_r_address0 = zext_ln102_fu_582_p1;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14))) begin
        buf_r_address0 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state13))) begin
        buf_r_address0 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state12))) begin
        buf_r_address0 = 64'd15;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11))) begin
        buf_r_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state10))) begin
        buf_r_address0 = 64'd13;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15))) begin
        buf_r_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        buf_r_address0 = grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_address0;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30))) begin
        buf_r_address0 = grp_aes_subBytes_1_fu_380_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_address0 = grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_address0;
    end else begin
        buf_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        buf_r_address1 = buf_r_addr_16_reg_1111;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        buf_r_address1 = buf_r_addr_17_reg_1097;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_address1 = buf_r_addr_14_reg_1072;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        buf_r_address1 = buf_r_addr_12_reg_1047;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_r_address1 = zext_ln102_1_fu_601_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_r_address1 = zext_ln100_fu_559_p1;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14))) begin
        buf_r_address1 = 64'd14;
    end else if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state13))) begin
        buf_r_address1 = 64'd11;
    end else if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state12))) begin
        buf_r_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11))) begin
        buf_r_address1 = 64'd10;
    end else if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state10))) begin
        buf_r_address1 = 64'd9;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15))) begin
        buf_r_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        buf_r_address1 = grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_address1 = grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_address1;
    end else begin
        buf_r_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state21))) begin
        buf_r_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        buf_r_ce0 = grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_ce0;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30))) begin
        buf_r_ce0 = grp_aes_subBytes_1_fu_380_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_ce0 = grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_ce0;
    end else begin
        buf_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state21))) begin
        buf_r_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        buf_r_ce1 = grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_ce1 = grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_ce1;
    end else begin
        buf_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_d0 = xor_ln105_3_reg_1087;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        buf_r_d0 = xor_ln104_4_fu_715_p2;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state20))) begin
        buf_r_d0 = reg_433;
    end else if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state19))) begin
        buf_r_d0 = reg_462;
    end else if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state18))) begin
        buf_r_d0 = reg_472;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state17))) begin
        buf_r_d0 = reg_452;
    end else if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state16))) begin
        buf_r_d0 = reg_428;
    end else if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15))) begin
        buf_r_d0 = reg_440;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        buf_r_d0 = grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_d0;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30))) begin
        buf_r_d0 = grp_aes_subBytes_1_fu_380_buf_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_d0 = grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_d0;
    end else begin
        buf_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        buf_r_d1 = xor_ln71_fu_911_p2;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        buf_r_d1 = xor_ln71_1_fu_841_p2;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_d1 = xor_ln105_1_reg_1082;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        buf_r_d1 = xor_ln104_1_fu_668_p2;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state20))) begin
        buf_r_d1 = reg_440;
    end else if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state19))) begin
        buf_r_d1 = reg_477;
    end else if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state18))) begin
        buf_r_d1 = reg_467;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state17))) begin
        buf_r_d1 = reg_457;
    end else if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state16))) begin
        buf_r_d1 = reg_447;
    end else if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15))) begin
        buf_r_d1 = reg_433;
    end else begin
        buf_r_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15))) begin
        buf_r_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        buf_r_we0 = grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_buf_r_we0;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30))) begin
        buf_r_we0 = grp_aes_subBytes_1_fu_380_buf_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_we0 = grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_buf_r_we0;
    end else begin
        buf_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state15) | ((trunc_ln148_reg_1068 == 1'd0) & (1'b1 == ap_CS_fsm_state27)))) begin
        buf_r_we1 = 1'b1;
    end else begin
        buf_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state30_on_subcall_done) & (1'b1 == ap_CS_fsm_state30)) | ((grp_aes_expandEncKey_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25)))) begin
        ctx_o = grp_aes_expandEncKey_fu_362_ap_return_0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        ctx_o = or_ln79_1_loc_fu_136;
    end else begin
        ctx_o = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((1'b0 == ap_block_state30_on_subcall_done) & (1'b1 == ap_CS_fsm_state30)) | ((grp_aes_expandEncKey_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25)))) begin
        ctx_o_ap_vld = 1'b1;
    end else begin
        ctx_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_aes_expandEncKey_fu_362_k_idx = 10'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_aes_expandEncKey_fu_362_k_idx = 10'd512;
    end else begin
        grp_aes_expandEncKey_fu_362_k_idx = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_aes_expandEncKey_fu_362_p_read = reg_411;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_aes_expandEncKey_fu_362_p_read = reg_417;
    end else begin
        grp_aes_expandEncKey_fu_362_p_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_aes_expandEncKey_fu_362_rc_read = reg_423;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_aes_expandEncKey_fu_362_rc_read = rcon_2_fu_128;
    end else begin
        grp_aes_expandEncKey_fu_362_rc_read = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln142_fu_500_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_aes_expandEncKey_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln148_fu_553_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((grp_aes_subBytes_1_fu_380_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (trunc_ln148_fu_593_p1 == 1'd1) & (tmp_fu_564_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else if (((1'b1 == ap_CS_fsm_state21) & (trunc_ln148_fu_593_p1 == 1'd0) & (tmp_fu_564_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state25 : begin
            if (((grp_aes_expandEncKey_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((1'b1 == ap_CS_fsm_state27) & ((icmp_ln71_1_fu_848_p2 == 1'd1) | (trunc_ln148_reg_1068 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((icmp_ln71_fu_918_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state30 : begin
            if (((1'b0 == ap_block_state30_on_subcall_done) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            if (((grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_fu_587_p2 = (i_15_reg_318 + 5'd4);

assign add_ln142_fu_510_p2 = ($signed(i_7_fu_124) + $signed(3'd7));

assign add_ln71_1_fu_813_p2 = ($signed(i_16_reg_329) + $signed(4'd15));

assign add_ln71_fu_878_p2 = ($signed(i_17_reg_341) + $signed(4'd15));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state30_on_subcall_done = ((grp_aes_subBytes_1_fu_380_ap_done == 1'b0) | (grp_aes_expandEncKey_fu_362_ap_done == 1'b0));
end

assign e_fu_628_p2 = (xor_ln103_1_fu_622_p2 ^ buf_r_q0);

assign grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start = grp_aes256_encrypt_ecb_Pipeline_addkey_fu_386_ap_start_reg;

assign grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start = grp_aes256_encrypt_ecb_Pipeline_cpkey_fu_372_ap_start_reg;

assign grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start = grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_ap_start_reg;

assign grp_aes_expandEncKey_fu_362_ap_start = grp_aes_expandEncKey_fu_362_ap_start_reg;

assign grp_aes_subBytes_1_fu_380_ap_start = grp_aes_subBytes_1_fu_380_ap_start_reg;

assign i_23_fu_863_p2 = (i_11_fu_140 + 4'd1);

assign icmp_ln142_fu_500_p2 = ((i_7_fu_124 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_553_p2 = ((i_11_fu_140 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln71_1_fu_848_p2 = ((i_16_reg_329 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_918_p2 = ((i_17_reg_341 == 4'd0) ? 1'b1 : 1'b0);

assign k_address0 = grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_k_address0;

assign k_ce0 = grp_aes256_encrypt_ecb_Pipeline_ecb1_fu_353_k_ce0;

assign lshr_ln71_1_fu_831_p2 = reg_482 >> zext_ln71_1_fu_827_p1;

assign lshr_ln71_fu_901_p2 = empty_24_fu_144 >> zext_ln71_2_fu_897_p1;

assign or_ln102_1_fu_596_p2 = (trunc_ln102_reg_1052 | 4'd2);

assign or_ln102_2_fu_606_p2 = (trunc_ln102_reg_1052 | 4'd3);

assign or_ln102_fu_576_p2 = (trunc_ln102_fu_572_p1 | 4'd1);

assign select_ln55_1_fu_701_p3 = ((tmp_35_fu_681_p3[0:0] == 1'b1) ? xor_ln55_1_fu_695_p2 : shl_ln55_1_fu_689_p2);

assign select_ln55_2_fu_748_p3 = ((tmp_36_fu_728_p3[0:0] == 1'b1) ? xor_ln55_2_fu_742_p2 : shl_ln55_2_fu_736_p2);

assign select_ln55_3_fu_794_p3 = ((tmp_37_fu_774_p3[0:0] == 1'b1) ? xor_ln55_3_fu_788_p2 : shl_ln55_3_fu_782_p2);

assign select_ln55_fu_654_p3 = ((tmp_34_fu_634_p3[0:0] == 1'b1) ? xor_ln55_fu_648_p2 : shl_ln55_fu_642_p2);

assign shl_ln55_1_fu_689_p2 = xor_ln104_2_fu_675_p2 << 8'd1;

assign shl_ln55_2_fu_736_p2 = xor_ln105_2_fu_722_p2 << 8'd1;

assign shl_ln55_3_fu_782_p2 = xor_ln105_4_fu_768_p2 << 8'd1;

assign shl_ln55_fu_642_p2 = xor_ln103_fu_616_p2 << 8'd1;

assign shl_ln71_1_fu_819_p3 = {{i_16_reg_329}, {3'd0}};

assign tmp_34_fu_634_p3 = xor_ln103_fu_616_p2[32'd7];

assign tmp_35_fu_681_p3 = xor_ln104_2_fu_675_p2[32'd7];

assign tmp_36_fu_728_p3 = xor_ln105_2_fu_722_p2[32'd7];

assign tmp_37_fu_774_p3 = xor_ln105_4_fu_768_p2[32'd7];

assign tmp_fu_564_p3 = i_15_reg_318[32'd4];

assign trunc_ln102_fu_572_p1 = i_15_reg_318[3:0];

assign trunc_ln148_fu_593_p1 = i_11_fu_140[0:0];

assign trunc_ln71_1_fu_837_p1 = lshr_ln71_1_fu_831_p2[7:0];

assign trunc_ln71_fu_907_p1 = lshr_ln71_fu_901_p2[7:0];

assign xor_ln103_1_fu_622_p2 = (xor_ln103_fu_616_p2 ^ buf_r_q1);

assign xor_ln103_fu_616_p2 = (reg_433 ^ reg_428);

assign xor_ln104_1_fu_668_p2 = (xor_ln104_fu_662_p2 ^ reg_428);

assign xor_ln104_2_fu_675_p2 = (reg_433 ^ buf_r_q1);

assign xor_ln104_3_fu_709_p2 = (select_ln55_1_fu_701_p3 ^ e_fu_628_p2);

assign xor_ln104_4_fu_715_p2 = (xor_ln104_3_fu_709_p2 ^ reg_433);

assign xor_ln104_fu_662_p2 = (select_ln55_fu_654_p3 ^ e_fu_628_p2);

assign xor_ln105_1_fu_762_p2 = (xor_ln105_fu_756_p2 ^ buf_r_q0);

assign xor_ln105_2_fu_722_p2 = (buf_r_q1 ^ buf_r_q0);

assign xor_ln105_3_fu_802_p2 = (xor_ln103_1_fu_622_p2 ^ select_ln55_3_fu_794_p3);

assign xor_ln105_4_fu_768_p2 = (reg_428 ^ buf_r_q0);

assign xor_ln105_fu_756_p2 = (xor_ln103_fu_616_p2 ^ select_ln55_2_fu_748_p3);

assign xor_ln55_1_fu_695_p2 = (shl_ln55_1_fu_689_p2 ^ 8'd27);

assign xor_ln55_2_fu_742_p2 = (shl_ln55_2_fu_736_p2 ^ 8'd27);

assign xor_ln55_3_fu_788_p2 = (shl_ln55_3_fu_782_p2 ^ 8'd27);

assign xor_ln55_fu_648_p2 = (shl_ln55_fu_642_p2 ^ 8'd27);

assign xor_ln71_1_fu_841_p2 = (trunc_ln71_1_fu_837_p1 ^ buf_r_q0);

assign xor_ln71_fu_911_p2 = (trunc_ln71_fu_907_p1 ^ buf_r_q0);

assign zext_ln100_fu_559_p1 = i_15_reg_318;

assign zext_ln102_1_fu_601_p1 = or_ln102_1_fu_596_p2;

assign zext_ln102_2_fu_611_p1 = or_ln102_2_fu_606_p2;

assign zext_ln102_fu_582_p1 = or_ln102_fu_576_p2;

assign zext_ln71_1_fu_827_p1 = shl_ln71_1_fu_819_p3;

assign zext_ln71_2_cast_fu_887_p4 = {{{{1'd1}, {i_17_reg_341}}}, {3'd0}};

assign zext_ln71_2_fu_897_p1 = zext_ln71_2_cast_fu_887_p4;

assign zext_ln71_3_fu_808_p1 = i_16_reg_329;

assign zext_ln71_fu_873_p1 = i_17_reg_341;

always @ (posedge ap_clk) begin
    buf_r_addr_13_reg_1058[0] <= 1'b1;
    buf_r_addr_14_reg_1072[1] <= 1'b1;
    buf_r_addr_15_reg_1077[1:0] <= 2'b11;
end

endmodule //aes256_encrypt_ecb
