#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("obs_address0", 8, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("obs_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("obs_q0", 8, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("init_address0", 6, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("init_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("init_q0", 64, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("transition_address0", 12, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("transition_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("transition_q0", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("transition_address1", 12, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("transition_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("transition_q1", 64, hls_in, 2, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("emission_address0", 12, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("emission_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("emission_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("path_address0", 8, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("path_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("path_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("path_d0", 8, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("path_address1", 8, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("path_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("path_q1", 8, hls_in, 4, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("ap_return", 32, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "viterbi";
