#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("tmax", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("nx", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("ny", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("ex_address0", 13, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("ex_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("ex_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("ex_d0", 64, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("ex_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("ex_address1", 13, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("ex_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("ex_q1", 64, hls_in, 3, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("ey_address0", 13, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("ey_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("ey_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("ey_d0", 64, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("ey_q0", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("ey_address1", 13, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("ey_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("ey_q1", 64, hls_in, 4, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("hz_address0", 13, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("hz_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("hz_we0", 1, hls_out, 5, "ap_memory", "mem_we", 1),
	Port_Property("hz_d0", 64, hls_out, 5, "ap_memory", "mem_din", 1),
	Port_Property("hz_q0", 64, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("hz_address1", 13, hls_out, 5, "ap_memory", "MemPortADDR2", 1),
	Port_Property("hz_ce1", 1, hls_out, 5, "ap_memory", "MemPortCE2", 1),
	Port_Property("hz_q1", 64, hls_in, 5, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("p_fict_s_address0", 6, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("p_fict_s_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("p_fict_s_q0", 64, hls_in, 6, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "fdtd_2d";
