#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_address0", 11, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("a_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("a_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("a_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("a_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("b_address0", 11, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("b_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("b_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("b_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("b_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("bucket_address0", 11, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("bucket_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("bucket_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("bucket_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("bucket_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("bucket_address1", 11, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("bucket_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("bucket_we1", 1, hls_out, 2, "ap_memory", "MemPortWE2", 1),
	Port_Property("bucket_d1", 32, hls_out, 2, "ap_memory", "MemPortDIN2", 1),
	Port_Property("bucket_q1", 32, hls_in, 2, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("sum_address0", 7, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("sum_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("sum_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("sum_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("sum_q0", 32, hls_in, 3, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "sort_radix";
